configuration:
  data_path: "/home/ygalvis/Documents/Study/ETL_Final/dags/Data/"
  file_name_input: "Dataset.csv"
  file_extension_input: "html, csv, txt"
  report_retention_days: 7
  url_file: "https://raw.githubusercontent.com/ygalves/ETL_project/refs/heads/main/Dataset/caso%20etl.csv"
  raw_table_name: "etl_dataset"
  transformed_table_name: "etl_transformed"
  eu_table: "eu"
  events_table: "events"
  lots_table: "lots"
  phases_table: "phases"
